### ISSUE TITLE
Limit On Module Trace Doesn't Work As Expected

### ISSUE THREAD

**Issue by OnorioCatenacci** [christhekeele/matcha#32]
Following the tracing livebook I tried the following (in iex):

```elixir
Matcha.Trace.module(Integer, limit: 5)
```

Then

```elixir
Integer.parse("1")
Integer.parse("2")
Integer.parse("3")
```

The recon tracer limit tripped after 3 instead of 5.

Here's the exact session:

```
onorio_developer@onorio-ubuntu:~/matcha$ iex -S mix
Erlang/OTP 25 [erts-13.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Interactive Elixir (1.14.0) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> Matcha.Trace.module(Integer, limit: 5)
#Matcha.Trace<Integer.:_/:any>
iex(2)> Integer.parse("1")
{1, ""}
        
12:53:16.630104 <0.287.0> 'Elixir.Integer':'__info__'(deprecated)
        
12:53:16.651171 <0.287.0> 'Elixir.Integer':parse(<<"1">>)
iex(3)> Integer.parse("2")
{2, ""}

12:53:22.874967 <0.287.0> 'Elixir.Integer':'__info__'(deprecated)
        
12:53:22.875216 <0.287.0> 'Elixir.Integer':parse(<<"2">>)
iex(4)> Integer.parse("3")
{3, ""}

12:53:29.956667 <0.287.0> 'Elixir.Integer':'__info__'(deprecated)
Recon tracer rate limit tripped.
iex(5)> 

```

**Comment by OnorioCatenacci** [comment]
Sorry--my bad.  Just misunderstood what counted toward the rate limit.  Sorry--please ignore this!

**Comment by christhekeele** [comment]
> The recon tracer limit tripped after 3 instead of 5.

> Just misunderstood what counted toward the rate limit.

I think it's worth calling out that this misunderstanding was caused by insuffient documentation—what do you think about adding a section early in the tracing docs that demonstrates and educates on how the rate limiter works?

**Comment by OnorioCatenacci** [comment]
That thought had crossed my mind.  In this case I simply had the wrong expectation of how it'd work but yeah it may be worth calling out what the rate limiter is actually counting.
