### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by axelson** [christhekeele/matcha#63]
I'd like to request a new release so I can publish my https://github.com/axelson/data_tracer package that uses Matcha :tada:

Currently I can't publish to hex because I'm using code that is only in GitHub and isn't on hex (hex only allows hex deps). Specifically I need https://github.com/christhekeele/matcha/commit/1620b0899481d6a7a9bf06c3a0d9ee025c4cd0ce from https://github.com/christhekeele/matcha/pull/47

**Comment by christhekeele** [comment]
Just released v`0.1.8`!

**Comment by axelson** [comment]
Awesome! Thanks!

Now I've published https://hex.pm/packages/data_tracer :tada:
